### ISSUE TITLE
correction rate of discriminator training

### ISSUE THREAD

**Issue by tengjiayan20** [alsdudrla10/DG_imagenet#1]
Your work is excellent!
I want to use DG in my diffusion model. But when I train the discriminator on Imagenet dataset, the correction rate fluctuates around 0.74 (The initial value is 0.71, and the increase after stabilization does not exceed 0.001). I wonder if there is something wrong. What is your normal correct rate during training?

**Comment by Kim-Dongjun** [comment]
Thank you for your interest. Could you visualize the correction rate by time? It could not drastically increase because at large time the correction rate would be 0.5 even for optimal discriminator.

**Comment by tengjiayan20** [comment]
It means that even optimal discriminator can't distinguish between real pictures and fake pictures？

**Comment by Kim-Dongjun** [comment]
at large time, yes.

**Comment by tengjiayan20** [comment]
Thanks!
