### ISSUE TITLE
Memory problems about 256 pixel space on ADM

### ISSUE THREAD

**Issue by tengjiayan20** [alsdudrla10/DG_imagenet#2]
When I deploy the DG method to the model of the ADM class, I face a huge challenge on both cpu and gpu. But you did not publish this part of the codes. Could you publish or email to show how to deploy 256pixel training? Looking forward to your reply! Thank you!

**Comment by Kim-Dongjun** [comment]
I don't remember how I did the experiment. But I share few tips for further study.

1. Extract classifier features (8x8) from high-dim images and save the features.
2. Train discriminator with features (8x8), not the original image (256x256).

This saves a tons of memory. Also, I ran my all codes on A100 with 80Gb, so I would recommend you to use the same machine.

**Comment by tengjiayan20** [comment]
Thank you! I understand.
